name: 'Package Checkup Action'
description: 'Check for vulnerable, outdated or unused dependencies'
author: 'Ian Sutherland'

inputs:
  showOutdatedPackages:
    description: 'Show outdated packages'
    default: true
    required: true
  showUnusedPackages:
    description: 'Show unused packages'
    default: true
    required: true
  showMissingPackages:
    description: 'Show missing packages'
    default: true
    required: true
  unusedIgnore:
    description: 'Ignore unused packages that match pattern'
    required: false
  missingIgnore:
    description: 'Ignore missing packages that match pattern'
    required: false
  token:
    description: 'GitHub authentication token'
    required: true

runs:
  using: 'node12'
  main: 'build/index.js'

branding:
  icon: 'activity'
  color: 'gray-dark'
