name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn --prefer-offline --frozen-lockfile --no-progress --non-interactive
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Commit build
        uses: endbug/add-and-commit@v4
        if: steps.changes.outputs.changed == 1
        with:
          add: 'build'
          message: 'Add build output'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
